import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/ReactQuery/provider";
import { UserManageProvider } from "@/Context/UserManageContext";
import { ProductsAndOrdersManageProvider } from "@/Context/Products&OrdersManageContext";
import Bar from "@/components/products/Bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],


});

export const metadata: Metadata = {
  title: "Sweetly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <UserManageProvider>
            <ProductsAndOrdersManageProvider>
              <div>
              {children}
              </div> 
              <div className="sticky bottom-0 left-0 right-0">
                <Bar/>
              </div>

            </ProductsAndOrdersManageProvider>
          </UserManageProvider>
        </Providers>
      </body>
    </html>
  );
}
